version: '3.3'

services:
  test-app:
    image: bb-information-mediator-api-image
    ports:
      - 3366:3003
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-bb-information-mediator.json:/mockoon-bb-information-mediator.json
