openapi: 3.0.0
info:
  title: GovStack IM Service Metadata API
  version: '0.3'
paths:
  /listClients:
    get:
      tags:
        - metaservices
      summary: List clients defined in the instance
      description: |
        Clients of the security server have the capability to obtain a list
        of potential service providers within a GovStack instance, including
        both members and applications.
        To do so, they should initiate an HTTP GET request to the security
        server.
        The specific request URL will be either `http://SECURITYSERVER/listClients`
        or `https://SECURITYSERVER/listClients`, depending on whether HTTPS
        protocol usage is enabled for interaction.

        When submitting this request, the placeholder `SECURITYSERVER` must be
        replased with the actual address of the security server. One can also
        retrieve a list of clients from other federated GovStack instances
        by adding an additional HTTP parameter:

          `instanceId` - a code of the instance.

        For instance, if you wish to fetch the list of clients associated with the
        instance labeled as `ABC`, your request URL should take the form of
        `http://SECURITYSERVER/listClients?instanceId=ABC`.
      operationId: listClients
      parameters:
        - name: instanceId
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of Clients of GovStack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restClientDetailsListType'
        '400':
          description: Error in request
        '500':
          description: Internal error
  /r1/{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/listMethods:
    parameters:
      - $ref: '#/components/parameters/GovStackInstance'
      - $ref: '#/components/parameters/memberClass'
      - $ref: '#/components/parameters/memberCode'
      - $ref: '#/components/parameters/applicationCode'
    get:
      tags:
        - metaservices
      summary: List REST services and endpoints for a service provider
      description: |
        This function provides a list of all REST services and service endpoints
        offered by a service provider.
        It's important to note that the endpoints could potentially include
        wildcard entries, and the actual number of specific endpoints might
        exceed what's listed here.
        Typically, retrieving the OpenAPI service description is the recommended
        approach for discovering service endpoints.
      operationId: listMethods
      parameters:
        - name: serviceId
          in: query
          schema:
            type: string
        - name: X-GovStack-Client
          in: header
          schema:
            type: string
      responses:
        '200':
          description: List of REST services and endpoints for a service provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restServiceDetailsListType'
        '400':
          description: Error in request
        '500':
          description: Internal error
  /r1/{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/allowedMethods:
    parameters:
      - $ref: '#/components/parameters/GovStackInstance'
      - $ref: '#/components/parameters/memberClass'
      - $ref: '#/components/parameters/memberCode'
      - $ref: '#/components/parameters/applicationCode'
    get:
      tags:
        - metaservices
      summary: List of allowed REST services and endpoints for a service provider
      description: |
        This function provides a list of REST services and service endpoints
        offered by a service provider that the caller has permission to invoke.
        It's important to note that the endpoints could potentially include
        wildcard entries, and the actual number of specific endpoints might
        exceed what's listed here.
        Typically, retrieving the OpenAPI service description is the recommended
        approach for discovering service endpoints.
      operationId: allowedMethods
      parameters:
        - name: serviceId
          in: query
          schema:
            type: string
        - name: X-GovStack-Client
          in: header
          schema:
            type: string
      responses:
        '200':
          description: List of allowed REST services and endpoints for a service provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restServiceDetailsListType'
        '400':
          description: Error in request
        '500':
          description: Internal error
  /r1/{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/getOpenAPI:
    parameters:
      - $ref: "#/components/parameters/GovStackInstance"
      - $ref: "#/components/parameters/memberClass"
      - $ref: "#/components/parameters/memberCode"
      - $ref: "#/components/parameters/applicationCode"
    get:
      tags:
        - metaservices
      summary: Returns OpenAPI service description for a REST service
      description: |
        This metaservice is designed to retrieve service descriptions for
        REST services.
        It provides the OpenAPI service description for a specific REST service.
        To use this service, the query parameters should include `serviceCode=xxx`,
        where `xxx` corresponds to the service code of the particular REST service
        for which you desire to obtain the service description.
      operationId: getOpenAPI
      parameters:
        - name: serviceCode
          in: query
          schema:
            type: string
        - name: X-GovStack-Client
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OpenAPI description of the specified REST service
          content:
            application/json:
              schema:
                type: string
            text/yaml:
              schema:
                type: string
        '400':
          description: Error in request
        '500':
          description: Internal error
components:
  parameters:
    GovStackInstance:
      name: GovStackInstance
      required: true
      in: path
      schema:
        type: string
    memberClass:
      name: memberClass
      required: true
      in: path
      schema:
        type: string
    memberCode:
      name: memberCode
      required: true
      in: path
      schema:
        type: string
    applicationCode:
      name: applicationCode
      required: true
      in: path
      schema:
        type: string
  schemas:
    restClientDetailsListType:
      type: object
      properties:
        member:
          type: array
          items:
            $ref: '#/components/schemas/restClientDetailsType'
    restClientDetailsType:
      type: object
      properties:
        name:
          type: string
        id:
          type: object
          properties:
            objectType:
              type: string
              enum:
                - MEMBER
                - APPLICATION
                - SERVICE
            GovStackInstance:
              type: string
            memberClass:
              type: string
            memberCode:
              type: string
            applicationCode:
              type: string
    restServiceDetailsListType:
      type: object
      properties:
        member:
          type: array
          items:
            $ref: '#/components/schemas/restServiceDetailsType'
    restServiceDetailsType:
      type: object
      properties:
        objectType:
          type: string
          enum:
            - MEMBER
            - APPLICATION
            - SERVICE
        serviceType:
          type: string
        GovStackInstance:
          type: string
        memberClass:
          type: string
        memberCode:
          type: string
        applicationCode:
          type: string
        serviceCode:
          type: string
        serviceVersion:
          type: string
        endpointList:
          type: object
          properties:
            member:
              type: array
              items:
                $ref: '#/components/schemas/endpoint'
    endpoint:
      type: object
      properties:
        method:
          type: string
        path:
          type: string
